# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Night Piece
subtitle: white && black
description: something about tech, android etc...
author: limuzhi
email: muzhi1991@gmail.com
language: zh-Hans
timezone:
avatar: /images/avatar.jpg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://limuzhi.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next
plugins:
- hexo-generator-cname

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:muzhi1991/muzhi1991.github.io.git
    coding: git@git.coding.net:muzhi1991/muzhi1991.git,coding-pages

# Social Links
social:
  github: https://github.com/muzhi1991
  twitter: https://twitter.com/muzhi1991
  weibo: http://weibo.com/muzhi1991
#  douban: http://douban.com/people/your-user-name
#  zhihu: http://www.zhihu.com/people/your-user-name

# title, chinese available
links_title: Links
# links
links:
  MacTalk: http://macshuo.com/

#comment
#disqus_shortname: muzhi1991
duoshuo_shortname: muzhi1991

#analytics
google_analytics: UA-73077297-1
baidu_analytics: 492ae7efb5ef95bf72321c8712d32a03

# hexo sitemap网站地图
sitemap:
path: sitemap.xml
baidusitemap:
path: baidusitemap.xml

